spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/student2
  username: postgres
  password: postgres
server:
  servlet:
   context-path: /ex-beginner
  
  
